---
author:   "Author: Daniel Carpenter"
date:     "`r format(Sys.Date(), '%B %d, %Y')`"
output: 
  github_document:
    toc: yes
  # html_document:
  #   toc: yes
  #   toc_float: yes
  #   toc_depth: 3
  #   theme: yeti
  #   fig_width: 7
  #   fig_height: 5
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%",
  echo    = TRUE, # Default only show output (not code)
	message = FALSE,
	warning = FALSE
)
```

# AdvRPackage

<!-- badges: start -->
<!-- badges: end -->

## Installation

You can install the development version of AdvRPackage from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("Daniel-Carpenter/AdvRPackage")
```

---

<br>

## Examples

### Packages
```{r packages}
library(devtools)    # check function
library(sloop)       # Checking the dispatch of functions
library(AdvRPackage) # My package: https://github.com/Daniel-Carpenter/AdvRPackage
```

### Testing the Package

#### `check` Function
```{r check}
# Check the current (or package) directory containing the R package
# devtools::check(".") 
```


#### Print Functions
```{r}
# myttest function
print(AdvRPackage::myttest)

# print method
print(AdvRPackage::print)
```


#### Create Sample Data
```{r data}
# X Variable
set.seed(21)
x <- rnorm(30,5,2)

# Y Variable
set.seed(23)
y <- rnorm(30, 3,2)

# Alpha level
alpha <- 0.05
```


#### Call the Constructor
```{r callConstructor}
# Call the contructor
obj <- AdvRPackage::myttest(x = x, y = y, alpha = 0.05)
```


#### Print the Output
```{r printing}
class(obj)
print(obj)
s3_dispatch( print(obj) ) # Note the dispatch
```


#### Plot the Output
```{r plots}
plot(obj)
s3_dispatch( plot(obj) ) # Note the dispatch
```
